server:
  port: 8101
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: example-api
  cloud:
    nacos:
      config:
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8001/oauth/token_key' # RSA公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
# logging config
logging:
  level:
    root: debug
    org:
      apache: info
      springframework: info
    com:
      alibaba:
        nacos: info