spring:
  cloud:
    nacos:
      config:
        file-extension: yml
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8001/oauth/token_key' # RSA公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
#  datasource:
#    url:  jdbc:mysql://localhost:3306/graphql_demo?characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: diboot
#    password: 123456
#    maximum-pool-size:  5
#    driver-class-name:  com.mysql.cj.jdbc.Driver

# logging config
logging:
  level:
    root: debug
    org:
      apache: info
      springframework: info
    com:
      alibaba:
        nacos: info

## diboot devtools config
diboot:
  core:
    init-sql: false
  devtools:
    codes-author: JerryMa
    codes-copyright:  www.dibo.ltd
    codes-version:  1.0
    output-path:  example-api/src/main/java/com/example/
    output-path-sql:  example-api/src/main/resources/
    output-path-frontend: ../diboot-antd-admin/
    enable-lombok:  true
    enable-swagger: false
    generate-mapper-xml:  false